/*=============================================================================
   CASA CONSTRUTOR - BANCO DE DADOS FIREBIRD
=============================================================================*/

/* GENERATORS */
CREATE GENERATOR GEN_PEDIDO;
SET GENERATOR GEN_PEDIDO TO 0;

CREATE GENERATOR GEN_PEDIDO_ITEM;
SET GENERATOR GEN_PEDIDO_ITEM TO 0;

/* TABELAS */

CREATE TABLE CLIENTE (
    CODIGO   INTEGER      NOT NULL,
    NOME     VARCHAR(100) NOT NULL,
    CIDADE   VARCHAR(60)  NOT NULL,
    UF       CHAR(2)      NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (CODIGO)
);

CREATE TABLE PRODUTO (
    CODIGO        INTEGER       NOT NULL,
    DESCRICAO     VARCHAR(150)  NOT NULL,
    PRECO_VENDA   NUMERIC(15,2) NOT NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY (CODIGO)
);

CREATE TABLE PEDIDO (
    NUMERO_PEDIDO   INTEGER       NOT NULL,
    DATA_EMISSAO    DATE          NOT NULL,
    CODIGO_CLIENTE  INTEGER       NOT NULL,
    VALOR_TOTAL     NUMERIC(15,2) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (NUMERO_PEDIDO),
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (CODIGO_CLIENTE)
        REFERENCES CLIENTE (CODIGO) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE PEDIDO_ITEM (
    ID              INTEGER       NOT NULL,
    NUMERO_PEDIDO   INTEGER       NOT NULL,
    CODIGO_PRODUTO  INTEGER       NOT NULL,
    QUANTIDADE      NUMERIC(10,3) NOT NULL,
    VLR_UNITARIO    NUMERIC(15,2) NOT NULL,
    VLR_TOTAL       NUMERIC(15,2) NOT NULL,
    CONSTRAINT PK_PEDIDO_ITEM PRIMARY KEY (ID),
    CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY (NUMERO_PEDIDO)
        REFERENCES PEDIDO (NUMERO_PEDIDO) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY (CODIGO_PRODUTO)
        REFERENCES PRODUTO (CODIGO) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE INDEX IDX_PEDIDO_CLIENTE ON PEDIDO (CODIGO_CLIENTE);
CREATE INDEX IDX_ITEM_PEDIDO    ON PEDIDO_ITEM (NUMERO_PEDIDO);

/* TRIGGERS */
SET TERM ^ ;

CREATE TRIGGER BI_PEDIDO FOR PEDIDO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.NUMERO_PEDIDO IS NULL) THEN
        NEW.NUMERO_PEDIDO = GEN_ID(GEN_PEDIDO, 1);
END^

CREATE TRIGGER BI_PEDIDO_ITEM FOR PEDIDO_ITEM
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = GEN_ID(GEN_PEDIDO_ITEM, 1);
END^

SET TERM ; ^

/* DADOS INICIAIS */

INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (1,  'Construtora Horizonte Ltda',      'São Paulo',        'SP');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (2,  'Obras e Reformas Brasil S/A',      'Rio de Janeiro',   'RJ');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (3,  'Empreiteira Norte Superior',       'Manaus',           'AM');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (4,  'Engenharia Planalto Ltda',         'Brasília',         'DF');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (5,  'Construtora Sol Nascente',         'Salvador',         'BA');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (6,  'Reformas e Acabamentos Curitiba',  'Curitiba',         'PR');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (7,  'Habitação Popular do Sul Ltda',    'Porto Alegre',     'RS');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (8,  'Centro-Oeste Construções ME',      'Goiânia',          'GO');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (9,  'Litoral Empreendimentos Ltda',     'Florianópolis',    'SC');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (10, 'Nordeste Engenharia e Projetos',   'Recife',           'PE');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (11, 'ArteCasa Construções',             'Belo Horizonte',   'MG');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (12, 'Sertão Forte Obras Ltda',         'Fortaleza',        'CE');

INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (1,  'Cimento CP-II 50kg',                    35.90);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (2,  'Tijolo Cerâmico 9 Furos (unidade)',      0.85);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (3,  'Areia Média (m³)',                      120.00);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (4,  'Brita Nº 1 (m³)',                       145.00);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (5,  'Ferro CA-50 Ø10mm (barra 12m)',          62.50);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (6,  'Telha Cerâmica Colonial (unidade)',       4.20);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (7,  'Tinta Látex Premium 18L',               189.90);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (8,  'Piso Cerâmico 60x60 (m²)',               75.00);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (9,  'Tubo PVC Esgoto 100mm (6m)',              48.00);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (10, 'Cabo Elétrico 2,5mm (rolo 100m)',       320.00);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (11, 'Argamassa Colante ACIII 20kg',           28.50);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (12, 'Porta de Madeira Maciça 80x210cm',      650.00);

COMMIT;